CHANNELS = [
    {"name": "KTV이매진",         "id": "UCj8Snyrs1y-wnBQiUmGrTjw"},
    {"name": "NATV_korea",        "id": "UCsWa6xl7KxOolVhROUJ4Ghw"},
    {"name": "이재명tv",           "id": "UCNJM6dqu70Qr6VaseiW1Org"},
    {"name": "dailyminjoo",       "id": "UCoQD2xsqwzJA93PTIYERokg"},
    {"name": "KTV_korea",         "id": "UCIMOytYIzaUpoAM2bpT4JZQ"},
    {"name": "MBCNEWS11",         "id": "UCF4Wxdo3inmxP-Y59wXDsFw"},
    {"name": "Jtvnews2021",       "id": "UCWGk_-J9WJxgFBAgJXi4ilA"},
    {"name": "g1tvnews",          "id": "UCx7D8prcWx7m8qy2xEiT7pA"},
    {"name": "mbcradio_sisa",     "id": "UCTTmtS2ljy1vyl_s-d_LEHQ"},
    {"name": "maebulshow",        "id": "UCMYhq9OyGI5UEz_NTAoHY7A"},
    {"name": "gyeomsonisnothing", "id": "UCAAvO0ehWox1bbym3rXKBZw"},
    {"name": "취재편의점",         "id": "UCAVVxLmPDFkSTROPue8ZrRA"},
    {"name": "SPEAKS_TV",         "id": "UCgeOlLcX6PReHdWImEnUVTg"},
    {"name": "daeannews",         "id": "UClgTJWXTyDDBVWr0g5LjR8w"},
    {"name": "HankyorehTV",       "id": "UCw7ZbT9Js4Vru6HSEk1NHyw"},
    {"name": "sisaineditor",      "id": "UCaVuYo_tiiNzTSmlnM-A2kQ"},
    {"name": "choikytv",          "id": "UCE-94tymU-LjuglJ_wqzhHA"},
    {"name": "사장남천동",         "id": "UCUFpe4kv7GRPEddLfCJOIzQ"},
    {"name": "kangsungbumTV",     "id": "UCMNGwNS4yCEsCCyu2soQDrQ"},
    {"name": "여의도옆문래동",     "id": "UC3cxhquPL-anKgzqj0ndzoA"},
    {"name": "백운기의정어리TV",   "id": "UCnj0yVadEmXKcUN5ztUY4uw"},
    {"name": "봉지욱기자",         "id": "UC9mEeE55q4PCfGERt_PNYbg"},
    {"name": "DHLeeTV",           "id": "UC3TdlUq20joza2kS0Nl0sSw"},
]
